### ISSUE TITLE
Running list of items to return to/think about

### ISSUE THREAD

**Issue by samanthacsik** [Openscapes/website-new#3]
## General
- [x] revisit what menu items we want to add/remove/rename (any "hidden" pages we want to bring to navbar?)
- [x] banner options (currently understand how to make banner image full size without text on top, or narrow with the ability to overlay text using yaml title option) -- need to fiddle more
- [x] centering images (e.g. all the little critters) -- currently using html `<center>` tag but should opt for css (I think technically that's the more correct way?)
- [x] fix hyperlinks (many will be broken until I make those pages)
- [x] `.qmd`s feel messy at the moment -- revisit style consistency 
- [x] find all [event page](https://openscapes.github.io/events/) links and update once migrated over to blog within main site

### Home
- [ ] icon alignment (want 3 side-by-side columns)
- [x] add text beneath 3 "our approach" icons 
- [x] centering images (mozilla & nceas) -- need to figure out css
- [x] figure out how to include recent blog post previews on home page 
- [x]  Learn More and Connect buttons at bottom of page need hyperlinks to appropriate pages once published

### Who are we?
- [x] update language under "Our website"
- [x] update event page link here: **which also sponsored the [first Champions Cohort](https://www.openscapes.org/cohorts)**

### Champions Program

- [ ] update events link under **Explore previous [Openscapes Champions Cohorts](https://openscapes.github.io/events/#category=Champions%20Cohort)....**
- [x] block quote styling still in the works

### Media

- [x] added intro placeholder text -- can edit and/or remove!

#### Media
- [x] [Using Git to Drive Better Science with Dr. Julie Lowndes](https://intertidal.agency/intertidal-podcast/2020/9/14/9-using-git-to-drive-better-science-with-dr-julie-lowndes) is a broken link -- updated with [this link instead](https://podcasts.apple.com/us/podcast/9-using-git-to-drive-better-science-with-dr-julie-lowndes/id1506653409?i=1000491609299) but want to **double check that it's correct**
- [x] [The coupling of innovation and open data science tools for science has been fascinating to me and hard to tease apart: An interview with Dr Julia Stewart Lowndes](https://www.statisticsviews.com/details/feature/11216365/The-coupling-of-innovation-and-open-data-science-tools-for-science-has-been-fasc.html) **link broken (haven't found working link yet)**

#### Lessons 
- [x] update links to blog posts (Tidy Data Illustrated Series, GitHub Illustrated Series)

#### Presentations 
- [x] [ESDSWG](https://wiki.earthdata.nasa.gov/display/ESDSWG/2022+ESDSWG+Meeting+Agenda) **link requires login?**
- [x] [Open Project Design: Lessons from the NASA Openscapes Framework](https://docs.google.com/presentation/d/1uc2BGBsjVABa_ZnqYCi8EgeFjlUSMd3KMSlQJnok9T8/edit?usp=sharing) — December 17, 2021: invited talk at the [Open Science in Action](https://agu.confex.com/agu/fm21/meetingapp.cgi/Session) Session at the AGU Fall meeting (30 minutes) **(Open Science in Action link no longer available, so I removed from new site)**
- [x] [How you can do better science in less time](https://docs.google.com/presentation/d/1EGSTC-p0kKCV3TNpc65Kyy1S0OOFmDalO917S0UIRvE/edit?usp=sharing) — March 5, 2021: University of South Florida – College of Marine Science Seminar Series with Dr. Marcus Beck: [Open science lessons from Tampa Bay ](https://www.canva.com/design/DAEXu-oE6M4/o4okxvLdSs6t3lrxfqApkA/edit#1)(20 minutes each) ([video](https://www.youtube.com/watch?v=21qS05Yv3GQ&t=195s)) -- **Open science lessons from Tampa Bay requires login**
- [x] [R and teamwork for better science in less time](https://openscapes.github.io/slides/betterscience/nwfsc#1) - November 19, 2020: [NOAA Northwest Fisheries Science Center](https://www.fisheries.noaa.gov/event/nwfsc-monster-seminar-jam-julia-stewart-lowndes), Seattle, Washington (45 minutes) (presented remotely) **NOAA Northwest Fisheries Science Center link broken, but updated with [this one]([R and teamwork for better science in less time](https://openscapes.github.io/slides/betterscience/nwfsc#1) - November 19, 2020: [NOAA Northwest Fisheries Science Center](https://www.fisheries.noaa.gov/event/nwfsc-monster-seminar-jam-julia-stewart-lowndes), Seattle, Washington (45 minutes) (presented remotely))**
- [x] [R for better science in less time: Lessons from the Ocean Health Index and Openscapes](https://docs.google.com/presentation/d/1LA4EcnRxD11rjwbRh0hrjPG5J0dmiiuCbNaoQrz0XHU/edit?usp=sharing) - November 21, 2019: [School of Aquatic and Fisheries Sciences, University of Washington](https://fish.uw.edu/news-events/events/), Seattle, Washington (45 minutes) ([video](https://www.youtube.com/watch?v=AML7V7P4s4A)) **video no longer available**
- [x] [R and friends for better science in less time in big (and small) team collaborations](https://openscapes.github.io/slides/betterscience/escience#1) - November 19, 2019: [eScience Institute](https://escience.washington.edu/data-science-seminar-11/), Seattle, Washington (45 minutes) ([video](https://www.youtube.com/watch?v=HjTLTiAWk1g&feature=youtu.be)) **eScience institute link broken, updated it with [this one](https://escience.washington.edu/)**
- [x] [How the Ocean Health Index enables better science in less time](https://docs.google.com/presentation/d/1vqUJpdfjEzFzlh-cAPcIpUBwhFsaMSqyjDhQUjh6aR8/edit#slide=id.g3601f799be_0_0) - April 15, 2019: Department Seminar, [Bren School of Environmental Science and Management](https://bren.ucsb.edu/), University of California, Santa Barbara, California (45 minutes) **Bren link broken, updated to [this one](https://bren.ucsb.edu/)**

### Connect

- [x] link Openscapes Champions Cohorts to updated website page once published (under OUR CURRENT PROJECTS)
- [x] update [event page](https://openscapes.github.io/events/) link
- [x] update presentations link under **Amplify through....**

### Team

- [x] updated Erin Robinson's personal website url to https://erinrobinson.info/ (was broken)
- [x] update link to Allison's gallery page (once created)
- [x] removed mention of Tara Robertson's Twitter (looks like she deleted her account)
- [x] updated link to Mozilla fellows page to https://foundation.mozilla.org/en/what-we-fund/fellowships-and-awards-directory/ (was broken)

### FAQ

- [x] still working on figuring out quoteblock css styling (vertical bar isn't appearing); for now, using gray box to signify quotes

### Resources
-  [x] need updated link for How to Start a Coding Club blog post, once ported: https://www.openscapes.org/blog/2018/11/16/how-to-start-a-coding-club/
- [x] need updated file path for Build Communities  blog post, once ported: https://www.openscapes.org/blog/2018/11/06/build-communities/
- [x] need updated file path for STARTING OUR #TIDYTUESDAY HACKY HOURS blog post, once ported: https://www.openscapes.org/blog/2019/05/02/tidy-tuesday-coding-club/
- [x] need updated file path for So you want to learn R blog post, once ported: https://www.openscapes.org/blog/2018/12/17/want-to-learn-r/

**Comment by jules32** [comment]
@samanthacsik for the 2 Media check-list items above: 

- "Using Git" - yes that is the correct new link
- "Coupling of innovation" - it's ok to just drop this from the media list

**Comment by samanthacsik** [comment]
Sounds great, updates made!

**Comment by samanthacsik** [comment]
Closing this issue and opening a revised TODO list issue here: https://github.com/Openscapes/website-new/issues/12
